Update DotNet.yml

diff --git a/.github/workflows/DotNet.yml b/.github/workflows/DotNet.yml
--- a/.github/workflows/DotNet.yml
+++ b/.github/workflows/DotNet.yml
@@ -19,6 +19,13 @@ jobs:
 
       - name: Display Current Directory
         run: ls
+
+      - name: Verify Dockerfile presence
+        run: |
+          if [ ! -f HamroCommunity/Dockerfile ]; then
+          echo "Dockerfile not found!"
+          exit 1
+          fi
         
       - name: Change to project directory and build
         run: |
